-- VHDL Entity my_project_lib.hex_block_diagram.symbol
--
-- Created:
--          by - Suzana.UNKNOWN (SUZANA-PC)
--          at - 20:54:59 27/02/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY hex_block_diagram IS
   PORT( 
      switch2 : IN     std_logic;
      switch3 : IN     std_logic;
      switch4 : IN     std_logic;
      switch5 : IN     std_logic;
      hex0    : OUT    std_logic_vector (6 DOWNTO 0);
      hex1    : OUT    std_logic_vector (6 DOWNTO 0);
      hex2    : OUT    std_logic_vector (6 DOWNTO 0);
      hex3    : OUT    std_logic_vector (6 DOWNTO 0);
      hex4    : OUT    std_logic_vector (6 DOWNTO 0);
      hex5    : OUT    std_logic_vector (6 DOWNTO 0);
      hex6    : OUT    std_logic_vector (6 DOWNTO 0);
      hex7    : OUT    std_logic_vector (6 DOWNTO 0)
   );

-- Declarations

END hex_block_diagram ;

--
-- VHDL Architecture my_project_lib.hex_block_diagram.struct
--
-- Created:
--          by - Suzana.UNKNOWN (SUZANA-PC)
--          at - 20:54:59 27/02/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY my_project_lib;

ARCHITECTURE struct OF hex_block_diagram IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT hexGenerator
   PORT (
      switch4 : IN     std_logic ;
      switch5 : IN     std_logic ;
      switch3 : IN     std_logic ;
      switch2 : IN     std_logic ;
      hex0    : OUT    std_logic_vector (6 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : hexGenerator USE ENTITY my_project_lib.hexGenerator;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_1' of 'vdd'
   hex1 <= (OTHERS => '1');

   -- ModuleWare code(v1.9) for instance 'U_2' of 'vdd'
   hex2 <= (OTHERS => '1');

   -- ModuleWare code(v1.9) for instance 'U_3' of 'vdd'
   hex3 <= (OTHERS => '1');

   -- ModuleWare code(v1.9) for instance 'U_4' of 'vdd'
   hex4 <= (OTHERS => '1');

   -- ModuleWare code(v1.9) for instance 'U_5' of 'vdd'
   hex5 <= (OTHERS => '1');

   -- ModuleWare code(v1.9) for instance 'U_6' of 'vdd'
   hex6 <= (OTHERS => '1');

   -- ModuleWare code(v1.9) for instance 'U_7' of 'vdd'
   hex7 <= (OTHERS => '1');

   -- Instance port mappings.
   U_0 : hexGenerator
      PORT MAP (
         switch4 => switch4,
         switch5 => switch5,
         switch3 => switch3,
         switch2 => switch2,
         hex0    => hex0
      );

END struct;
