-- VHDL Entity my_project_lib.lcd_de2115.symbol
--
-- Created:
--          by - Suzana.UNKNOWN (SUZANA-PC)
--          at - 21:03:47 27/02/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY lcd_de2115 IS
   PORT( 
      pushButtons : IN     std_logic_vector (3 DOWNTO 0);
      switchs     : IN     std_logic_vector (17 DOWNTO 0);
      hex0        : OUT    std_logic_vector (6 DOWNTO 0);
      hex1        : OUT    std_logic_vector (6 DOWNTO 0);
      hex2        : OUT    std_logic_vector (6 DOWNTO 0);
      hex3        : OUT    std_logic_vector (6 DOWNTO 0);
      hex4        : OUT    std_logic_vector (6 DOWNTO 0);
      hex5        : OUT    std_logic_vector (6 DOWNTO 0);
      hex6        : OUT    std_logic_vector (6 DOWNTO 0);
      hex7        : OUT    std_logic_vector (6 DOWNTO 0);
      ledG        : OUT    std_logic_vector (8 DOWNTO 0);
      ledR        : OUT    std_logic_vector (17 DOWNTO 0)
   );

-- Declarations

END lcd_de2115 ;

--
-- VHDL Architecture my_project_lib.lcd_de2115.struct
--
-- Created:
--          by - Suzana.UNKNOWN (SUZANA-PC)
--          at - 21:03:47 27/02/2016
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY my_project_lib;

ARCHITECTURE struct OF lcd_de2115 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL switch0  : std_logic;
   SIGNAL switch1  : std_logic;
   SIGNAL switch10 : std_logic;
   SIGNAL switch11 : std_logic;
   SIGNAL switch12 : std_logic;
   SIGNAL switch13 : std_logic;
   SIGNAL switch14 : std_logic;
   SIGNAL switch15 : std_logic;
   SIGNAL switch16 : std_logic;
   SIGNAL switch17 : std_logic;
   SIGNAL switch2  : std_logic;
   SIGNAL switch3  : std_logic;
   SIGNAL switch4  : std_logic;
   SIGNAL switch5  : std_logic;
   SIGNAL switch6  : std_logic;
   SIGNAL switch7  : std_logic;
   SIGNAL switch8  : std_logic;
   SIGNAL switch9  : std_logic;


   -- ModuleWare signal declarations(v1.9) for instance 'U_2' of 'split'
   SIGNAL mw_U_2temp_din : std_logic_vector(17 DOWNTO 0);

   -- Component Declarations
   COMPONENT hex_block_diagram
   PORT (
      switch2 : IN     std_logic ;
      switch3 : IN     std_logic ;
      switch4 : IN     std_logic ;
      switch5 : IN     std_logic ;
      hex0    : OUT    std_logic_vector (6 DOWNTO 0);
      hex1    : OUT    std_logic_vector (6 DOWNTO 0);
      hex2    : OUT    std_logic_vector (6 DOWNTO 0);
      hex3    : OUT    std_logic_vector (6 DOWNTO 0);
      hex4    : OUT    std_logic_vector (6 DOWNTO 0);
      hex5    : OUT    std_logic_vector (6 DOWNTO 0);
      hex6    : OUT    std_logic_vector (6 DOWNTO 0);
      hex7    : OUT    std_logic_vector (6 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT leds_block
   PORT (
      switch1 : IN     std_logic;
      LED0    : OUT    std_logic;
      LED1    : OUT    std_logic;
      LED2    : OUT    std_logic;
      LED3    : OUT    std_logic;
      LED4    : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : hex_block_diagram USE ENTITY my_project_lib.hex_block_diagram;
   FOR ALL : leds_block USE ENTITY my_project_lib.leds_block;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 turnLedsOn
   ledR(0) <= '1';
   ledR(1) <= '1';
   ledR(2) <= '1';
   ledR(3) <= '1';
                                                                                
   
   


   -- ModuleWare code(v1.9) for instance 'U_2' of 'split'
   mw_U_2temp_din <= switchs;
   u_2combo_proc: PROCESS (mw_U_2temp_din)
   VARIABLE temp_din: std_logic_vector(17 DOWNTO 0);
   BEGIN
      temp_din := mw_U_2temp_din(17 DOWNTO 0);
      switch0 <= temp_din(0);
      switch1 <= temp_din(1);
      switch2 <= temp_din(2);
      switch3 <= temp_din(3);
      switch4 <= temp_din(4);
      switch5 <= temp_din(5);
      switch6 <= temp_din(6);
      switch7 <= temp_din(7);
      switch8 <= temp_din(8);
      switch9 <= temp_din(9);
      switch10 <= temp_din(10);
      switch11 <= temp_din(11);
      switch12 <= temp_din(12);
      switch13 <= temp_din(13);
      switch14 <= temp_din(14);
      switch15 <= temp_din(15);
      switch16 <= temp_din(16);
      switch17 <= temp_din(17);
   END PROCESS u_2combo_proc;

   -- Instance port mappings.
   U_1 : hex_block_diagram
      PORT MAP (
         switch2 => switch0,
         switch3 => switch1,
         switch4 => switch2,
         switch5 => switch3,
         hex0    => hex0,
         hex1    => hex1,
         hex2    => hex2,
         hex3    => hex3,
         hex4    => hex4,
         hex5    => hex5,
         hex6    => hex6,
         hex7    => hex7
      );
   U_0 : leds_block
      PORT MAP (
         LED0    => OPEN,
         LED1    => OPEN,
         LED2    => OPEN,
         LED3    => OPEN,
         LED4    => OPEN,
         switch1 => switch0
      );

END struct;
